### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by TheBountyHunters** [darrylb123/usbrelay#66]
I want to control this over Web Browser Instead of UI on IP address (Ethernet) Any Solution?

**Comment by darrylb123** [comment]
It would be hard to do securely given the we server needs permission to
operate USB. Not impossible though. Could be done with udev rules to set
the permission and an old style CGI script to send the commands.
One day I'll add an mqtt interface so that home assistant or node red could
be used.

Darryl

**Comment by darrylb123** [comment]
I've added an mqtt interface. The relays can now be controlled by Home Assistant or NodeRed
